### ISSUE TITLE
E steps

### ISSUE THREAD

**Issue by RudyBenner** [SecKit/Marlin2.0#1]
BMG extruder.
Attached files.
Over extruding by a factor of 2.
Lines 835 to 858
The installed value is 392.4 when what is expected is 196.2.
Once changed, extrusion is perfect.

[RudyBenner_Config_Files.zip](https://github.com/SecKit/Marlin2.0/files/4157460/RudyBenner_Config_Files.zip)

**Comment by RudyBenner** [comment]
I suspect indentation. 842 and likewise 853

**Comment by SecKit** [comment]
There was a bug in fixed in commit 7eaef94 where E0_DRIVER_TYPE was wrongly defined to TMC2130 and should be TMC2209. Please download the latest version.

**Comment by RudyBenner** [comment]
Unrelated.
